name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t thenameisonkars/hello-world:latest .

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.thenameisonkars }}
        password: ${{ secrets.Meena@3458 }}

    - name: Push Docker image
      run: |
        docker push thenameisonkars/hello-world:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.hello-demo }}
        HOST: ${{ secrets.3.129.195.91 }}
        USER: ${{ secrets.ubuntu }}
      run: |
        ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" "$USER@$HOST" << 'EOF'
          docker pull thenameisonkars/hello-world:latest
          docker stop $(docker ps -q --filter ancestor=thenameisonkars/hello-world:latest) || true
          docker run -d -p 5000:5000 thenameisonkars/hello-world:latest
